### ISSUE TITLE
Support for Visual Studio 2015

### ISSUE THREAD

**Issue by kawazoe** [jedmao/tabsanity-vs#10]
Could you publish a build in the VS2015 RC extension gallery?

**Comment by jedmao** [comment]
Sorry. I have no plans to do that until the final version of VS 2015.

**Comment by kawazoe** [comment]
Ok, I can understand that. I will run my own build in the mean time.

**Comment by jedmao** [comment]
@kawazoe the VS 2015 version is up now!

**Comment by TeaDrivenDev** [comment]
@jedmao That's awesome; thanks a lot! I can switch now. :-)
