### ISSUE TITLE
VS 2013

### ISSUE THREAD

**Issue by webanck** [jedmao/tabsanity-vs#13]
Hello, I was very happy to find your extension but so sad when I tried to use it in VS 2013.
I simply can't, because it requires the 2015 version.
I tried to build it from your sources and the 2013 sln file. I even installed the 2013 SDK but I can'tg manage to build it.
Could you please compile a version of the 2013 variation?

**Comment by jedmao** [comment]
Sorry @webanck. Maybe if you tell me what the error or problem was with you trying to compile the source on your machine I could help w/ that, but I'm afraid I really don't want to install VS 2013 on my machine, so that's not an option.

**Comment by FlipB** [comment]
I've built this with the 2013 SDK successfully (just had to change some references).
I could upload it to the extensions gallery, but I'd need to create a new VSIX ID, and @jedmao permission, ofc!

**Comment by jedmao** [comment]
@FlipB I'm assuming your build works only on VS 2013? If so, I don't think I can publish it to [the gallery](https://visualstudiogallery.msdn.microsoft.com/ac4d4d6b-b017-4a42-8f72-55f0ffe850d7) w/o overwriting the 2015 version. This is the part of the publishing process that's always confused me, even after reading [Walkthrough: Publishing a Visual Studio Extension](https://msdn.microsoft.com/en-us/library/ff728613.aspx) and [Supporting Multiple Versions of Visual Studio](https://msdn.microsoft.com/en-us/library/bb164578.aspx).

As such, maybe it's a good idea to just put it in a public OneDrive folder and give people access to the VSIX file that way? I've done similar in the past. What do you think?

**Comment by jedmao** [comment]
Or I can just upload the VSIX file directly to this repo.

**Comment by FlipB** [comment]
I'm not sure how to publish extensions for multiple versions. I suppose you could try uploading the 2013 VSIX to the gallery?

Whatever you want to do, I've uploaded it here: https://github.com/FlipB/tabsanity-vs/blob/master/TabSanity.vsix

**Comment by jedmao** [comment]
Thanks @FlipB! I've added the file to this repo and a link on the readme. See https://github.com/jedmao/tabsanity-vs#installing.

**Comment by webanck** [comment]
@jedmao @FlipB : Thanks a lot!
