### ISSUE TITLE
Support for Visual Studio 2019 (preview?)

### ISSUE THREAD

**Issue by jukkahyv** [jedmao/tabsanity-vs#24]
Thank you for this wonderful plugin. I have started using Visual Studio 2019 Preview at work (it seems mostly stable), and this is the plugin that I miss the most. It would be great to see this updated to support VS2019 when possible.

**Comment by jedmao** [comment]
Not going to happen on my end. I've moved to vscode. Feel free to fork it.

**Comment by DrEthan77** [comment]
@jukkahyv i am working on porting it rn

**Comment by DrEthan77** [comment]
@jedmao k i have a pull request up and running :D

**Comment by DrEthan77** [comment]
[TabSanity_vsix.zip](https://github.com/jedmao/tabsanity-vs/files/3099656/TabSanity_vsix.zip)

**Comment by jukkahyv** [comment]
I installed it from the marketplace. Seems to be working fine. Thank you!
